# Change these first
owner: jeakob # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: BBC
    url: https://www.bbc.co.uk
  - name: KASM
    url: $KASM
    type: globalping
    __dangerous__body_down: "Host Error"
  - name: KASM1
    url: $KASM
    __dangerous__body_down: "Cloudflare"
  - name: KASM2
    url: $KASM
    __dangerous__body_down_if_text_missing: '"status":"UP"'

  - name: KASM3
    url: $KASM
    __dangerous__body_down: "301 Moved Permanently"

  - name: KASM4
    url: $KASM
    __dangerous__body_down: "Bad gateway"

  - name: PORTAINER
    url: $PORTAINER 

  
assignees:
  - jeakob

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Is it up?
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
